### ISSUE TITLE
Uploading node_modules folder

### ISSUE THREAD

**Issue by ibrahimraimi** [Ahuoyiza/firstServer#5]
Hey @Ahuoyiza the node_modules folder that contains your project dependencies  is not suppose to be uploaded to github.
## Reason
The main reason is that the node_modules contains a lot of installed  dependencies which can scale up to 200 megabits in size.
## Solution
Create a .gitignore file in your project directory and add in the path to your node_modules folder so when you are pushing to github, git will automatically ignore the node_modules folder.

**Comment by Ahuoyiza** [comment]
Thanks! Didn't get back to fix this. My first mistake as a beginner
